[tool.poetry]
name = "django"
version = "0.1.0"
description = ""
authors = ["DanyVolkof <dvolkov1999@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
shop = "^0.0.2"
blog = "^1.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
