#!/bin/bash

# Перейти в директорию с проектом
cd /path/to/your/django/project

# Активировать виртуальное окружение 
source /django/Scripts/activate

# Установить зависимости
pip install -r poetry.lock

# Применить миграции базы данных
python manage.py migrate

# Запустить сервер Django
python manage.py runserver